language: ruby
env:
  global:
    secure: GtEKx8uRTUer5aVXZQ23iKhzE9aYtLwQzbuRFsvqjfaLZ9M7yKHuQtZIP1QDFfLZHolYI4jKqUfVDIEdvOqMBx9JoLXsMkRTowPd+hrrAneKcFA1MUCPSBltp9DgZ0XSXsqQJ6dB0DxMEUfYUJH/yR8E/UZgjQzfi7/4rUfNTZYDTJRRvwD50cQClbfagyhBqmaTMKji12BaUE1RI6LXSon2Eh6RQQ2AVcZ5OG3yCYsYEe/b+FE5X5UuVv80GUb2eJsLr/caNpb5nUec1qoCGLyswy/GBGbh9rGnc9k2Pa/4PLOLKYoOsUBX51EazKuYRUtAIWj4QspL9kzYOZ5/RIEkt1cgyBn+1KQfxMITqVlkzxZtIYQUVYX7OUpoLjgaumPx3uVZVs8s54KyGXUNowQI9fR3HjQt8ltzzXn2MdtVHq/7FNK15dAnJYDpdgWazFw8aEj2gjB31PUyVQFw2a7EZvtRh2iONzn/0K8hzvKo5v+7JrnQNBIuPVOVfQpMeY7NJioJZNbAxiDGHgSwKuH8W7WYDjv6OCNMvBKmhFrvFhbh+KE5NAojh27CTFSJSnc3qN5Yl8vIN31x2H3I7nqq6i0jPDKKIqoJ8606I9z06gs1CUVkG5jQSQOlq57i9bDFnSTwH4RpbaqIVrMb4t2imdA5Ah6uG8GY4Js9gkY=
script: bundle exec middleman build --verbose && bundle exec middleman s3_sync
branches:
  only:
    - master
