name: Trigger Netlify Build
on:
  schedule:
    # Run at 0815 daily
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK_URL
